#Database
spring:
  datasource:
    # url: jdbc:postgresql://postgres:5432/chicago_db
    # username: chicago
    # password: 1q2w3e

    url: jdbc:postgresql://localhost:5432/fakenews
    username: postgres
    password: seho

    #Connection Pool
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10

  #JPA
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual: true